[workspace]
authors = ["Jordane Thomas <thomasjordane7@gmail.com>"]
channels = ["conda-forge"]
name = "scripts"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
rust = ">=1.95.0,<1.96"
python = ">=3.14.4,<3.15"
jupyterlab = ">=4.5.7,<5"

[pypi-dependencies]
kicad-skip = ">=0.2.5, <0.3"
